### PR TITLE
biome fix revert because ppl complain

### PR DESCRIPTION
**Pull request by Gordon-Dry**
Squad should fix their own shit themselves

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
What "wierd biome issues"?

**Comment by Gordon-Dry** [comment]
Well, he complained that geiger counters are biome dependant, he assumed that they should be only situation bound.
I insisted that only two measures in low and high space for a whole planet are not what scientists do, but he still complained.
However, you can ignore this.

Or ask in the forum what ppl think.

And ask Squad if they can say anything about it.

**Comment by linuxgurugamer** [comment]
I don't see a problem leaving it in as is.  One person complaining, is not enough to force a change.  I happen to agree with you on this, so, unless there is a big response, I'm going to leave this for now

**Comment by linuxgurugamer** [comment]
Closing this because I don't think it needs to be reverted.
Thanks

**Pull request closed without merging**
