### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by tinygrox**
I do some localized changes to your code.Hope it helps

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Appreciated

**Comment by linuxgurugamer** [comment]
Thank you for the work.  I must point out to you, however, that you uploaded the Localization directory to the root of the repo, not in the release directory.  As a result, the mod has been broken the past 3 days (I wasn't aware until today).
Please be aware and double-check what you do in the future.

**Comment by tinygrox** [comment]
I'm sorry for the mess. I don't know the way that work.Now I am be aware.I'll pay attention next time.

**Comment by linuxgurugamer** [comment]
It's not a problem, just caught me by surprise.
I do appreciate the work that you did, thank you

**Pull request merged**
