### PR TITLE
Simplify biome filter

### PR DESCRIPTION
**Pull request by jefftimlin**
There was a lot of code in the BiomeFilter class that attempted to generate a clean biome texture for the purposes of more accurate biome detection, however it's expensive and complicated. I changed it to do the generation on a background thread in the past to fix a lag issue when entering flight mode, but recently it has been crashing for me when used with other mods, such as Galileo's Planet Pack. I'm not exactly sure why, but I think it's a timing issue that only is coming up depending on other mods installed.

I've completely removed all of the complex code from this class to avoid the issue entirely, and just made it use the ScienceUtil.GetExperimentBiome function, which seems to work well. It makes the code faster, simpler, and safer.

I also fixed an array index out of bounds problem in RequiresCrew.cs, which I found while debugging, which would intermittently produce errors in the logs.

### CODE REVIEW

**Comment by jefftimlin** [comment]
Sorry, I found some problems with this, so I'll close it. Sorry for the hassle.

**Comment by linuxgurugamer** [comment]
No hassle, sorry you weren't able to fix it
What sort of problems did you find?

**Comment by jefftimlin** [comment]
The `ScienceUtil.GetExperimentBiome` method didn't seem to be working properly. It was returning "Highlands" at the GSC and even once I flew out over the water. I'm not sure why, perhaps the coordinates are wrong somehow. I had got the idea to use the function from the way it's [done in MechJeb](https://github.com/MuMech/MechJeb2/blob/cc520d12e76410d4a4ed29687cdc7882f17ed0f9/MechJeb2/CelestialBodyExtensions.cs#L66) which seems to work fine, so I'm not sure why that's not working here.

I wasn't able to come up with another solution to fix the threading code here. It seems to be that the call to `newBody.BiomeMap.GetAtt(lat, lon).mapColor` isn't always safe to call on a background thread, which is what's crashing, but for me it only happens when using GPP.

**Comment by linuxgurugamer** [comment]
Glad you found the problem. 
You are making enough major changes, I'm going to have to review this first.
Good catch on the issue with the i++

**Comment by linuxgurugamer** [comment]
Also, where were you getting the crashes when using GPP?

**Comment by jefftimlin** [comment]
Whenever launching any rocket from the VAB, just as it enters the flight scene.

**Comment by jefftimlin** [comment]
If you mean where in the code, well it's hard to say. It's an access violation that I was able to narrow down to the code on the background thread in the biome filter that tries to get the map colours from the biome map.

**Comment by linuxgurugamer** [comment]
Well, it seems I've been hitting that bug in my game, so I'll be able to test it.
Thanks, I'll be working on this sometime this evening, probably while streaming

**Comment by linuxgurugamer** [comment]
Given how old this mod is (originally back in 2014), I'm going to make a guess that the function that you are using wasn't available back when this mod was originally written.

I did notice a number of comments on the forums about this:

ScienceUtil.GetExperimentBiome

not sure if they are relevant, 

https://forum.kerbalspaceprogram.com/index.php?/search/&q=ScienceUtil.GetExperimentBiome&page=1&search_and_or=or&sortby=relevancy

**Comment by linuxgurugamer** [comment]
I'm merging this into a new branch for testing

**Pull request merged**
